// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn3Vz-24qCeKAudVVXPYjcQDPq94O37Ac',
    appId: '1:379265156647:android:fba8aff15fe00bb5387002',
    messagingSenderId: '379265156647',
    projectId: 'drup-logistics',
    storageBucket: 'drup-logistics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDxGLWNCjkVDNk7ast21X9raLXpXyKYHQ',
    appId: '1:379265156647:ios:cd45c092272bb4ea387002',
    messagingSenderId: '379265156647',
    projectId: 'drup-logistics',
    storageBucket: 'drup-logistics.firebasestorage.app',
    androidClientId: '379265156647-4jhcumf9ekt6e3e6plbtb16t254lj6qs.apps.googleusercontent.com',
    iosClientId: '379265156647-4fu0sis6gokcc85tar5h5vl7rv9a5bsi.apps.googleusercontent.com',
    iosBundleId: 'com.drup.app',
  );

}